server:
  port: 8999
  
eureka:
  instance:
    hostname: localhost
  client:
    enabled: true

spring:
  application:
    name: api-gateway
  cloud:
     gateway:
         routes:
           - id: user-service
             uri: lb://user-service
             predicates: 
                - Path=/users/**
             filters:
               - name: CircuitBreaker
                 args:  
                   name: user-service
                   fallbackuri: forword:/userServiceFallback
                     
                
           - id : contact-service
             uri: lb://contact-service
             predicates :
                 - Path=/contacts/**
             filters:
               - name: CircuitBreaker
                 args: 
                   name: contact-service
                   fallbackuri: forword:/contactServiceFallback
            
hystrix:
  command:
     fallbackcmd:
       execution:
         isolations:
           thread:
             timeoutInMillieseconds: 5000
             
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
        
  

      
       
        
